"""Measure a generated 72–88 px fighter cut against SMS render/stream limits.

This diagnostic describes source-derived candidates; it is not a delivery gate
and does not replace the ROM/emulator checks.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
from collections import Counter
from pathlib import Path

SPRITE_LINE_MAX = 8
SAT_MAX = 64
SPRITE_META_BYTES_CURRENT = 40
SPRITE_PATTERN_BYTES_CURRENT = 8192
STREAM_CHUNK_BYTES = 64
PATTERN_TILE_BYTES = 32


def mirrored_origin_x(anchor_x: int, axis_x: int, width_px: int) -> int:
    """Anchor a left-facing METAL on its padded 8px sprite-column grid."""
    padded_width = (int(width_px) + 7) & ~7
    return int(anchor_x) - (int(axis_x) + padded_width)


def raster_origin_x(anchor_x: int, axis_x: int, width_px: int, facing_left: bool) -> int:
    """Return the visible image origin, excluding left-side mirror padding."""
    if not facing_left:
        return int(anchor_x) + int(axis_x)
    padded_width = (int(width_px) + 7) & ~7
    return mirrored_origin_x(anchor_x, axis_x, width_px) + padded_width - int(width_px)


def _arrays(header: str) -> dict[str, bytes]:
    pattern = re.compile(
        r"(?:static\s+)?const unsigned char\s+(\w+)\s*\[(\d+)\]\s*=\s*\{(.*?)\};",
        re.S,
    )
    output = {}
    for name, size, body in pattern.findall(header):
        values = [int(token, 0) for token in
                  re.findall(r"0x[0-9A-Fa-f]+|\b\d+\b", body)]
        if len(values) != int(size) or any(value > 255 for value in values):
            raise ValueError(f"generated byte array is malformed: {name}")
        output[name] = bytes(values)
    aliases = dict(re.findall(
        r"^#define\s+([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*$", header, re.M))
    for alias in aliases:
        resolved = alias
        seen = set()
        while resolved in aliases:
            if resolved in seen:
                raise ValueError(f"generated array alias cycle: {alias}")
            seen.add(resolved)
            resolved = aliases[resolved]
        if alias.endswith(("_META", "_METAL")):
            if resolved not in output:
                raise ValueError(f"generated metadata alias target is missing: {alias}")
            output[alias] = output[resolved]
    return output


def _signed8(value: int) -> int:
    return value - 256 if value >= 128 else value


def _sprite_entries(data: bytes, facing: int, origin_x: int, origin_y: int) -> list[dict]:
    if not data or data[-1] != 0x80 or (len(data) - 1) % 3:
        raise ValueError("malformed generated metasprite")
    result = []
    for offset in range(0, len(data) - 1, 3):
        result.append({"x": origin_x + _signed8(data[offset]),
                       "y": origin_y + _signed8(data[offset + 1]),
                       "tile": data[offset + 2]})
    return result


def _screen_metrics(sprites: list[dict], screen_h: int = 192) -> dict:
    lines: Counter[int] = Counter()
    for sprite in sprites:
        y = int(sprite["y"])
        for line in range(max(0, y), min(y + 16, screen_h)):
            lines[line] += 1
    peak_line = max(lines.values(), default=0)
    peak_y = next((line for line, count in sorted(lines.items())
                   if count == peak_line), None)
    errors = []
    if len(sprites) > SAT_MAX:
        errors.append(f"SAT overflow: {len(sprites)} > {SAT_MAX}")
    if peak_line > SPRITE_LINE_MAX:
        errors.append(f"scanline overflow: {peak_line} > {SPRITE_LINE_MAX}")
    if any((int(sprite["y"]) + 1) & 0xFF == 0xD0 for sprite in sprites):
        errors.append("sprite Y collides with SAT terminator 0xD0")
    return {"sat_entries": len(sprites), "peak_sprites_per_scanline": peak_line,
            "peak_scanline": peak_y, "violations": errors}


def _fighter_poses(prefix: str, manifest: dict, arrays: dict[str, bytes],
                   origin_x: int, floor_y: int, facing: int, palette: str,
                   pattern_sizes: dict[str, int]) -> dict[tuple[int, int], dict]:
    if palette not in ("p1", "p2"):
        raise ValueError(f"unsupported fighter palette: {palette}")
    poses = {}
    for role in manifest["roles"]:
        action = int(role["action"])
        for frame_index in range(int(role["frame_count"])):
            stem = f"{prefix}_A{action}F{frame_index}"
            meta_name = stem + ("_P2" if palette == "p2" else "") + (
                "_METAL" if facing else "_META")
            axis_blob = arrays.get(stem + "_AXIS")
            meta_blob = arrays.get(meta_name)
            if axis_blob is None or len(axis_blob) != 4 or meta_blob is None:
                raise ValueError(f"generated pose metadata is missing: {stem}")
            axis_x, axis_y = struct.unpack("<hh", axis_blob)
            frame = manifest["frames"][f"anim:{action}.{frame_index}"]
            width, _height = frame["size_runtime"]
            screen_x = (mirrored_origin_x(origin_x, axis_x, width) if facing
                        else origin_x + axis_x)
            screen_y = floor_y + axis_y
            # A padded column is transparent at the left after mirroring; the
            # meta-grid origin and the unpadded raster origin are distinct.
            raster_x = raster_origin_x(origin_x, axis_x, width, bool(facing))
            sprites = _sprite_entries(meta_blob, facing, screen_x, screen_y)
            poses[(action, frame_index)] = {
                "role": role["role"], "action": action, "frame": frame_index,
                "duration_air": frame["duration_air"],
                "stream_ticks": frame["stream_ticks"],
                "render_origin": [screen_x, screen_y],
                "raster_origin": [raster_x, screen_y],
                "size_runtime": [width, frame["size_runtime"][1]],
                "pose_bytes": pattern_sizes.get(
                    stem + ("_P2_TILES" if palette == "p2" else "_TILES"), 0),
                "sprites": sprites,
                "metrics": _screen_metrics(sprites),
            }
    return poses


def _stream_mismatches(fighter: str, manifest: dict) -> list[dict]:
    rows = []
    for key, data in manifest["frames"].items():
        action, frame = map(int, key.removeprefix("anim:").split("."))
        air = int(data["duration_air"])
        stream = int(data["stream_ticks"])
        if air >= 0 and air < stream:
            rows.append({"fighter": fighter, "action": action, "frame": frame,
                         "air_ticks": air, "stream_ticks": stream})
    return rows


def _tile_family_metrics(frames: list[tuple[int, bytes]]) -> dict:
    if any(len(data) % PATTERN_TILE_BYTES for _, data in frames):
        raise ValueError("pose pattern payload is not a whole number of 32-byte tiles")
    all_tiles = [data[i:i + PATTERN_TILE_BYTES]
                 for _, data in frames
                 for i in range(0, len(data), PATTERN_TILE_BYTES)]
    transitions = []
    for (frame_a, data_a), (frame_b, data_b) in zip(frames, frames[1:]):
        shared_len = min(len(data_a), len(data_b))
        changed = sum(data_a[i:i + PATTERN_TILE_BYTES] !=
                      data_b[i:i + PATTERN_TILE_BYTES]
                      for i in range(0, shared_len, PATTERN_TILE_BYTES))
        changed += abs(len(data_a) - len(data_b)) // PATTERN_TILE_BYTES
        transitions.append({"from_frame": frame_a, "to_frame": frame_b,
                            "changed_tile_slots": changed})
    unique = set(all_tiles)
    return {
        "frames": len(frames),
        "payload_bytes_per_frame": [len(data) for _, data in frames],
        "family_payload_bytes": sum(len(data) for _, data in frames),
        "total_tile_slots": len(all_tiles),
        "unique_patterns": len(unique),
        "unique_pool_bytes": len(unique) * PATTERN_TILE_BYTES,
        "adjacent_transitions": transitions,
    }


def _pattern_match_counts(pattern: bytes, candidates: list[bytes]) -> tuple[int, int]:
    """Count exact and silhouette-mask matches for one 8x16 pair."""
    if len(pattern) != 64 or any(len(candidate) != 64 for candidate in candidates):
        raise ValueError("8x16 pattern-pair matching requires 64-byte inputs")

    def opacity_mask(data: bytes) -> bytes:
        return bytes(1 if nibble else 0
                     for value in data
                     for nibble in (value & 0x0F, value >> 4))

    target_mask = opacity_mask(pattern)
    exact_matches = sum(candidate == pattern for candidate in candidates)
    mask_matches = sum(opacity_mask(candidate) == target_mask
                       for candidate in candidates)
    return exact_matches, mask_matches


def _p2_metadata_reconstruction_probe(prefix: str, manifest: dict,
                                       arrays: dict[str, bytes], header_text: str,
                                       image_data: bytes, bank_start: int,
                                       bank_count: int) -> dict:
    """Check whether P1 META patterns occur in each P2 pose pool unchanged."""
    macros = {name: int(value) for name, value in re.findall(
        r"^#define\s+(\w+)\s+(\d+)\s*$", header_text, re.M)}

    def pose_patterns(stem: str, variant: str) -> list[bytes]:
        symbol = stem + variant
        try:
            size = macros[symbol + "_SIZE"]
            bank = macros[symbol + "_BANK"]
            offset = macros[symbol + "_OFF"]
        except KeyError as exc:
            raise ValueError(f"missing pose pool macro: {exc.args[0]}") from exc
        if not bank_start <= bank < bank_start + bank_count:
            raise ValueError(f"pose bank outside mapper image: {symbol}")
        if offset + size > 16384 or size % 64:
            raise ValueError(f"malformed pose pool: {symbol}")
        begin = (bank - bank_start) * 16384 + offset
        payload = image_data[begin:begin + size]
        if len(payload) != size:
            raise ValueError(f"truncated pose pool: {symbol}")
        return [payload[i:i + 64] for i in range(0, size, 64)]

    frames_checked = 0
    poses_exact = 0
    unique_pairs_checked = 0
    exact_pairs = 0
    mask_only_pairs = 0
    unmatched_pairs = 0
    examples = []
    for role in manifest["roles"]:
        action = int(role["action"])
        for frame_index in range(int(role["frame_count"])):
            stem = f"{prefix}_A{action}F{frame_index}"
            p1_patterns = pose_patterns(stem, "_TILES")
            p2_patterns = pose_patterns(stem, "_P2_TILES")
            frame_exact = True
            for suffix in ("_META", "_METAL"):
                meta = arrays.get(stem + suffix)
                if meta is None or not meta or meta[-1] != 0x80 or (len(meta) - 1) % 3:
                    raise ValueError(f"missing or malformed P1 metadata: {stem + suffix}")
                referenced = {meta[pos + 2] // 2
                              for pos in range(0, len(meta) - 1, 3)}
                for pair_index in referenced:
                    source_pair = p1_patterns[pair_index]
                    exact_matches, mask_matches = _pattern_match_counts(
                        source_pair, p2_patterns)
                    unique_pairs_checked += 1
                    if exact_matches:
                        exact_pairs += 1
                    elif mask_matches:
                        mask_only_pairs += 1
                        frame_exact = False
                        if len(examples) < 12:
                            examples.append({"action": action, "frame": frame_index,
                                             "facing": "right" if suffix == "_META" else "left",
                                             "source_pair_sha256": hashlib.sha256(source_pair).hexdigest(),
                                             "p2_exact_matches": exact_matches,
                                             "p2_opacity_mask_matches": mask_matches})
                    else:
                        unmatched_pairs += 1
                        frame_exact = False
                        if len(examples) < 12:
                            examples.append({"action": action, "frame": frame_index,
                                             "facing": "right" if suffix == "_META" else "left",
                                             "source_pair_sha256": hashlib.sha256(source_pair).hexdigest(),
                                             "p2_exact_matches": 0,
                                             "p2_opacity_mask_matches": 0})
            frames_checked += 1
            poses_exact += bool(frame_exact)
    return {
        "method": "compare each P1-referenced 8x16 byte pair with every 8x16 pair in the same pose P2 pool; also compare per-pixel opacity masks",
        "poses_checked": frames_checked,
        "poses_with_all_referenced_pairs_exact_in_p2_pool": poses_exact,
        "referenced_pair_indices_checked": unique_pairs_checked,
        "exact_pair_matches": exact_pairs,
        "opacity_only_matches": mask_only_pairs,
        "no_opacity_match": unmatched_pairs,
        "metadata_reconstructable_by_exact_pair_reuse": unmatched_pairs == 0 and mask_only_pairs == 0,
        "examples_of_non_exact_pairs": examples,
        "scope": "does not infer layout from similar silhouettes or prove source animation semantics; exact matches only can safely reuse P1 pattern references",
    }


def _joint_resident_pattern_count(first_nonshared: int, first_shared: set[bytes] | frozenset,
                                 second_nonshared: int, second_shared: set[bytes] | frozenset) -> int:
    """Count two actors' resident pools after exact byte-identical reuse."""
    return int(first_nonshared) + int(second_nonshared) + len(set(first_shared) | set(second_shared))


def _transition_cache_metrics(current: set[bytes], following: set[bytes],
                              air_ticks: int,
                              chunk_bytes: int = STREAM_CHUNK_BYTES) -> dict:
    """Measure exact next-pose bytes to prefetch while the current pose displays."""
    if any(len(pattern) != PATTERN_TILE_BYTES * 2
           for pattern in current | following):
        raise ValueError("transition cache expects exact 64-byte 8x16 pairs")
    new_patterns = following - current
    upload_bytes = len(new_patterns) * PATTERN_TILE_BYTES * 2
    ticks = int(air_ticks)
    if chunk_bytes < 1:
        raise ValueError("prefetch chunk must be positive")
    required_per_vblank = ((upload_bytes + ticks - 1) // ticks
                           if ticks > 0 else None)
    return {
        "current_pairs": len(current),
        "next_pairs": len(following),
        "reused_pairs": len(current & following),
        "new_pairs": len(new_patterns),
        "next_pose_upload_bytes": upload_bytes,
        "current_plus_next_resident_bytes": len(current | following) * PATTERN_TILE_BYTES * 2,
        "air_ticks_available": ticks,
        "minimum_uniform_upload_bytes_per_vblank": required_per_vblank,
        "assumed_chunk_bytes_per_vblank": chunk_bytes,
        "fits_assumed_chunk": (required_per_vblank is not None and
                                required_per_vblank <= chunk_bytes),
    }


def _remap_compact_metadata(metadata: bytes | list[int],
                            pair_slots: list[int]) -> bytes:
    """Map compact even tile IDs to physical 8x16 pair slots, preserving XY."""
    source = bytes(metadata)
    if not source or source[-1] != 0x80 or (len(source) - 1) % 3:
        raise ValueError("metadata must use dx/dy/tile triples and end in 0x80")
    if any(slot < 0 or slot > 0x7F for slot in pair_slots):
        raise ValueError("8x16 pair slot must fit the 128-pair SMS sprite table")
    remapped = bytearray(source)
    for pos in range(0, len(source) - 1, 3):
        compact_tile = source[pos + 2]
        if compact_tile & 1:
            raise ValueError("compact 8x16 tile ID must be even")
        compact_pair = compact_tile // 2
        if compact_pair >= len(pair_slots):
            raise ValueError("metadata references a missing compact pattern pair")
        remapped[pos + 2] = pair_slots[compact_pair] * 2
    if (remapped[:-1:3] != source[:-1:3] or
            remapped[1:-1:3] != source[1:-1:3] or
            remapped[-1] != source[-1]):
        raise AssertionError("physical slot remap changed coordinates or terminator")
    return bytes(remapped)


def _idle_cache_plan(poses: dict[tuple[int, int, str], dict], role: dict,
                     facing: str, slot_base: int, slot_count: int) -> dict:
    """Plan exact source-to-VRAM loads for a looping idle pose sequence."""
    action = int(role["action"])
    frame_count = int(role["frame_count"])
    loop_start = int(role.get("loop_start", 0))
    if frame_count < 1 or not 0 <= loop_start < frame_count:
        raise ValueError("idle cache plan needs a valid looping AIR role")
    if slot_base < 0 or slot_count < 1 or slot_base + slot_count > 128:
        raise ValueError("idle cache reservation exceeds the SMS 8x16 pair table")
    states = [poses[(action, index, facing)] for index in range(frame_count)]
    if any(len(state["selected_patterns"]) > slot_count for state in states):
        raise ValueError("one idle pose exceeds its reserved physical pair slots")
    slots = list(range(slot_base, slot_base + slot_count))

    def source_loads(state: dict, pattern_slots: dict[bytes, int]) -> list[dict]:
        loads = []
        for pattern, source_pair in zip(
                state["selected_patterns"],
                state["selected_pattern_source_pair_indices"]):
            if len(pattern) != PATTERN_TILE_BYTES * 2:
                raise ValueError("idle cache source pair is not exactly 64 bytes")
            source_off = int(state["pattern_off"]) + int(source_pair) * 64
            if source_off < 0 or source_off + 64 > 16384:
                raise ValueError("idle pair source range crosses its 16 KiB mapper page")
            loads.append({
                "source_bank": int(state["pattern_bank"]),
                "source_off": source_off,
                "source_pair_index": int(source_pair),
                "target_pair_slot": pattern_slots[pattern],
                "bytes": 64,
            })
        return loads

    def slot_rows(state: dict, pattern_slots: dict[bytes, int]) -> list[dict]:
        return [{
            "pattern_sha256": hashlib.sha256(pattern).hexdigest(),
            "source_pair_index": int(source_pair),
            "target_pair_slot": pattern_slots[pattern],
        } for pattern, source_pair in zip(
            state["selected_patterns"],
            state["selected_pattern_source_pair_indices"])]

    first = states[0]
    current_slots = {pattern: slots[index]
                     for index, pattern in enumerate(first["selected_patterns"])}
    initial_pose = {
        "action": action, "frame": 0, "facing": facing,
        "air_ticks": int(first["air_ticks"]),
        "axis_bytes": list(first["axis_bytes"]),
        "axis_signed_xy": list(first["axis_signed_xy"]),
        "metadata": list(_remap_compact_metadata(
            first["compact_metadata"],
            [current_slots[pattern] for pattern in first["selected_patterns"]])),
        "pattern_slots": slot_rows(first, current_slots),
        "pattern_loads": source_loads(first, current_slots),
    }
    transitions = []
    for frame_index, current in enumerate(states):
        next_index = (frame_index + 1 if frame_index + 1 < frame_count
                      else loop_start)
        following = states[next_index]
        following_slots = {pattern: current_slots[pattern]
                           for pattern in following["selected_patterns"]
                           if pattern in current_slots}
        occupied = set(current_slots.values())
        free_slots = [slot for slot in slots if slot not in occupied]
        new_patterns = [pattern for pattern in following["selected_patterns"]
                        if pattern not in following_slots]
        if len(new_patterns) > len(free_slots):
            raise ValueError("idle current+next poses exceed reserved cache slots")
        for pattern, slot in zip(new_patterns, free_slots):
            following_slots[pattern] = slot

        uploads = source_loads(following, following_slots)
        uploads = [load for load, pattern in zip(
            uploads, following["selected_patterns"]) if pattern not in current_slots]
        transition_metrics = _transition_cache_metrics(
            set(current["selected_patterns"]), set(following["selected_patterns"]),
            int(current["air_ticks"]))
        if len(uploads) * 64 != transition_metrics["next_pose_upload_bytes"]:
            raise AssertionError("idle slot plan upload bytes diverge from exact pair delta")
        remapped = _remap_compact_metadata(
            following["compact_metadata"],
            [following_slots[pattern] for pattern in following["selected_patterns"]])
        transitions.append({
            "from_frame": frame_index, "to_frame": next_index,
            "air_ticks_available": int(current["air_ticks"]),
            "next_air_ticks": int(following["air_ticks"]),
            "next_axis_bytes": list(following["axis_bytes"]),
            "next_axis_signed_xy": list(following["axis_signed_xy"]),
            "next_metadata": list(remapped),
            "next_pattern_slots": slot_rows(following, following_slots),
            "reused_pair_count": transition_metrics["reused_pairs"],
            "new_pair_count": len(uploads),
            "upload_bytes": len(uploads) * 64,
            "minimum_uniform_upload_bytes_per_vblank":
                transition_metrics["minimum_uniform_upload_bytes_per_vblank"],
            "uploads": uploads,
        })
        current_slots = following_slots

    peak_current_next = max(
        len(set(current["selected_patterns"]) |
            set(states[(i + 1 if i + 1 < frame_count else loop_start)]["selected_patterns"]))
        for i, current in enumerate(states))
    return {
        "status": "source_derived_candidate_not_runtime_proved",
        "role": role["role"], "action": action, "facing": facing,
        "frame_count": frame_count, "loop_start": loop_start,
        "reserved_pair_slots": {"first": slot_base, "count": slot_count,
                                "last_inclusive": slot_base + slot_count - 1},
        "reserved_vram_bytes": slot_count * 64,
        "initial_pose": initial_pose,
        "transitions": transitions,
        "maximum_current_plus_next_unique_pairs": peak_current_next,
        "maximum_current_plus_next_bytes": peak_current_next * 64,
        "authored_axis_and_air_values_preserved": True,
        "authored_dx_dy_and_terminators_preserved": True,
        "exact_source_pair_bytes_preserved": True,
        "scope": "deterministic cyclic idle cache allocation; each next pose reuses byte-identical current pairs and stages only missing 8x16 pairs into free reserved slots; no VBlank throughput or emulator timing claim",
    }


def _idle_family_tile_pool(root: Path, combined: dict,
                           manifests: dict[str, dict], header_text: str) -> dict:
    images = combined.get("mapper_images") or []
    if len(images) != 1:
        raise ValueError("scale pilot expects one consolidated mapper image")
    image = images[0]
    image_path = Path(image["path"])
    if not image_path.is_absolute():
        workspace_path = Path.cwd() / image_path
        image_path = workspace_path if workspace_path.is_file() else root / image["file"]
    data = image_path.read_bytes()
    if len(data) != int(image["bytes"]):
        raise ValueError("consolidated mapper image length diverges from manifest")
    bank_start = int(image["bank_start"])
    bank_count = int(image["bank_count"])
    results = {}
    union_patterns: set[bytes] = set()
    for fighter, prefix, variant in (
            ("ken", "KENMASTERSADV", "_TILES"),
            ("ryu", "RYU_KANG", "_P2_TILES")):
        manifest = manifests[fighter]
        role = next(row for row in manifest["roles"] if row["role"] == "idle")
        action = int(role["action"])
        frames = []
        for frame in range(int(role["frame_count"])):
            stem = f"{prefix}_A{action}F{frame}{variant}"
            macros = {}
            for suffix in ("_SIZE", "_BANK", "_OFF"):
                name = stem + suffix
                match = re.search(rf"^#define\s+{re.escape(name)}\s+(\d+)\s*$",
                                  header_text, re.M)
                if not match:
                    raise ValueError(f"missing idle pose bank macro: {name}")
                macros[suffix] = int(match.group(1))
            size, bank, offset = macros["_SIZE"], macros["_BANK"], macros["_OFF"]
            if not bank_start <= bank < bank_start + bank_count:
                raise ValueError(f"idle pose bank outside consolidated image: {stem}")
            start = (bank - bank_start) * 16384 + offset
            payload = data[start:start + size]
            if len(payload) != size:
                raise ValueError(f"idle pose payload exceeds mapper image: {stem}")
            frames.append((frame, payload))
        metrics = _tile_family_metrics(frames)
        unique = {payload[i:i + PATTERN_TILE_BYTES]
                  for _, payload in frames
                  for i in range(0, len(payload), PATTERN_TILE_BYTES)}
        union_patterns.update(unique)
        results[fighter] = {"pattern_variant": variant, **metrics}
    combined_bytes = len(union_patterns) * PATTERN_TILE_BYTES
    return {
        "families": results,
        "combined_unique_patterns": len(union_patterns),
        "combined_unique_pool_bytes": combined_bytes,
        "available_sprite_pattern_vram_bytes": SPRITE_PATTERN_BYTES_CURRENT,
        "all_idle_frames_fit_as_exact_tile_pool":
            combined_bytes <= SPRITE_PATTERN_BYTES_CURRENT,
        "scope": "exact 4bpp pattern-byte identity for Ken P1 and Ryu P2 idle frames; excludes metasprite metadata, runtime buffers, FX and other actions",
    }


def _selected_facing_pose_metrics(prefix: str, fighter: str, palette: str,
                                  manifest: dict, arrays: dict[str, bytes],
                                  header_text: str, image_data: bytes,
                                  bank_start: int, bank_count: int) -> dict:
    """Compact one facing and prove its metasprite still addresses identical art."""
    variant = "_P2_TILES" if palette == "p2" else "_TILES"
    poses = {}
    for role in manifest["roles"]:
        action = int(role["action"])
        for frame_index in range(int(role["frame_count"])):
            stem = f"{prefix}_A{action}F{frame_index}"
            frame_record = manifest["frames"][f"anim:{action}.{frame_index}"]
            axis_name = stem + "_AXIS"
            axis = arrays.get(axis_name)
            if axis is None or len(axis) != 4:
                raise ValueError(f"missing or malformed authored pivot: {axis_name}")
            axis_xy = struct.unpack("<hh", axis)
            for facing, base_suffix in (("right", "_META"), ("left", "_METAL")):
                p2_meta_name = stem + ("_P2" + base_suffix)
                base_meta_name = stem + base_suffix
                meta_name = (p2_meta_name if palette == "p2" and
                             p2_meta_name in arrays else base_meta_name)
                palette_metadata_verified = palette != "p2" or meta_name == p2_meta_name
                meta = arrays.get(meta_name)
                if meta is None or not meta or meta[-1] != 0x80 or (len(meta) - 1) % 3:
                    raise ValueError(f"malformed facing metasprite: {meta_name}")

                tile_symbol = stem + variant
                macros = {}
                for suffix in ("_SIZE", "_BANK", "_OFF"):
                    name = tile_symbol + suffix
                    match = re.search(rf"^#define\s+{re.escape(name)}\s+(\d+)\s*$",
                                      header_text, re.M)
                    if not match:
                        raise ValueError(f"missing facing pose bank macro: {name}")
                    macros[suffix] = int(match.group(1))
                size, bank, offset = macros["_SIZE"], macros["_BANK"], macros["_OFF"]
                if not bank_start <= bank < bank_start + bank_count:
                    raise ValueError(f"facing pose bank outside mapper image: {tile_symbol}")
                if offset < 0 or offset + size > 16384:
                    raise ValueError(f"facing pose crosses mapper page: {tile_symbol}")
                start = (bank - bank_start) * 16384 + offset
                payload = image_data[start:start + size]
                if len(payload) != size or size % 64:
                    raise ValueError(f"malformed facing pose payload: {tile_symbol}")

                old_ids = []
                old_patterns = {}
                for pos in range(0, len(meta) - 1, 3):
                    old_id = meta[pos + 2]
                    if old_id & 1:
                        raise ValueError(f"odd tall-sprite tile id in {meta_name}: {old_id}")
                    pair_index = old_id // 2
                    pattern_start = pair_index * 64
                    pattern = payload[pattern_start:pattern_start + 64]
                    if len(pattern) != 64:
                        raise ValueError(f"metasprite tile id outside {tile_symbol}: {old_id}")
                    old_ids.append(old_id)
                    old_patterns[old_id] = pattern

                compact_ids = {}
                compact_patterns = []
                pattern_to_id = {}
                pattern_source_pair = {}
                for old_id in old_ids:
                    pattern = old_patterns[old_id]
                    new_id = pattern_to_id.get(pattern)
                    if new_id is None:
                        new_id = len(compact_patterns) * 2
                        if new_id > 0xFE:
                            raise ValueError(f"compact facing exceeds tall-sprite index range: {meta_name}")
                        pattern_to_id[pattern] = new_id
                        compact_patterns.append(pattern)
                        pattern_source_pair[pattern] = old_id // 2
                    compact_ids[old_id] = new_id

                rewritten = bytearray(meta)
                for pos in range(0, len(meta) - 1, 3):
                    # X/Y retain their authored anchor-relative coordinates.
                    rewritten[pos + 2] = compact_ids[meta[pos + 2]]
                if rewritten[:-1:3] != meta[:-1:3] or rewritten[1:-1:3] != meta[1:-1:3]:
                    raise AssertionError("facing compaction changed metasprite coordinates")
                if any(old_patterns[old_id] != compact_patterns[compact_ids[old_id] // 2]
                       for old_id in old_ids):
                    raise AssertionError("facing compaction changed a referenced 8x16 pattern")

                key = (action, frame_index, facing)
                poses[key] = {
                    "fighter": fighter, "palette": palette, "facing": facing,
                    "action": action, "frame": frame_index, "role": role["role"],
                    "air_ticks": int(frame_record["duration_air"]),
                    "axis_bytes": list(axis),
                    "axis_signed_xy": list(axis_xy),
                    "source_pose_bytes": size,
                    "selected_patterns": compact_patterns,
                    "selected_pattern_source_pair_indices": [
                        pattern_source_pair[pattern] for pattern in compact_patterns],
                    "selected_pairs": len(compact_patterns),
                    "selected_bytes": len(compact_patterns) * 64,
                    "metadata_bytes": len(meta),
                    "compact_metadata": list(rewritten),
                    "pattern_bank": bank,
                    "pattern_off": offset,
                    "pattern_size": size,
                    "palette_metadata_verified": palette_metadata_verified,
                    "metadata_remap_exact": bytes(rewritten[:-1:3]) == bytes(meta[:-1:3]) and
                                            bytes(rewritten[1:-1:3]) == bytes(meta[1:-1:3]),
                    "pattern_remap_exact": True,
                }
    return poses


def _facing_pool_audit(root: Path, combined: dict,
                       manifests: dict[str, dict], arrays: dict[str, bytes],
                       header_text: str) -> dict:
    """Measure compact active-facing pools and conservative two-pose residency."""
    image = (combined.get("mapper_images") or [])[0]
    image_path = Path(image["path"])
    if not image_path.is_absolute():
        workspace_path = Path.cwd() / image_path
        image_path = workspace_path if workspace_path.is_file() else root / image["file"]
    image_data = image_path.read_bytes()
    if len(image_data) != int(image["bytes"]):
        raise ValueError("consolidated mapper image length diverges from facing audit")
    bank_start = int(image["bank_start"])
    bank_count = int(image["bank_count"])

    all_poses = {}
    fighter_specs = {"ken": ("KENMASTERSADV", "ken"),
                     "ryu": ("RYU_KANG", "ryu")}
    pilot_profiles = {"p1": "ken", "p2": "ryu"}
    rejected_variants = []
    for palette, fighter in pilot_profiles.items():
        prefix, manifest_key = fighter_specs[fighter]
        all_poses[(fighter, palette)] = _selected_facing_pose_metrics(
            prefix, fighter, palette, manifests[manifest_key], arrays,
            header_text, image_data, bank_start, bank_count)

    variant_compatibility = {}
    for fighter, (prefix, manifest_key) in fighter_specs.items():
        for palette in ("p1", "p2"):
            key = f"{fighter}_{palette}"
            if (fighter, palette) in all_poses:
                rows = all_poses[(fighter, palette)].values()
                metadata_available = all(
                    row["palette_metadata_verified"] for row in rows)
                variant_compatibility[key] = {
                    "status": "measured" if metadata_available else
                              "measured_layout_metadata_unverified",
                    "used_in_pilot_matchup": True,
                    "palette_specific_metadata_present": metadata_available,
                }
                continue
            try:
                unused_poses = _selected_facing_pose_metrics(
                    prefix, fighter, palette, manifests[manifest_key], arrays,
                    header_text, image_data, bank_start, bank_count)
                metadata_available = all(
                    row["palette_metadata_verified"] for row in unused_poses.values())
                variant_compatibility[key] = {
                    "status": "measured" if metadata_available else
                              "index_range_pass_metadata_unverified",
                    "used_in_pilot_matchup": False,
                    "palette_specific_metadata_present": metadata_available,
                }
            except ValueError as exc:
                variant_compatibility[key] = {
                    "status": "blocked_index_or_payload_mismatch",
                    "used_in_pilot_matchup": False,
                    "palette_specific_metadata_present": False,
                    "reason": str(exc),
                }
                rejected_variants.append({"variant": key, "reason": str(exc)})

    variants = {}
    for (fighter, palette), poses in all_poses.items():
        for facing in ("right", "left"):
            rows = [pose for pose in poses.values() if pose["facing"] == facing]
            worst = max(rows, key=lambda pose: pose["selected_bytes"])
            unique_patterns = {pattern for row in rows
                               for pattern in row["selected_patterns"]}
            stream_rows = [row for row in rows if row["air_ticks"] > 0]
            timing_mismatches = [row for row in stream_rows
                                 if (row["selected_bytes"] + STREAM_CHUNK_BYTES - 1) //
                                 STREAM_CHUNK_BYTES > row["air_ticks"]]
            variants[f"{fighter}_{palette}_{facing}"] = {
                "poses": len(rows),
                "worst_pose": {key: worst[key] for key in
                               ("action", "frame", "role", "selected_pairs",
                                "selected_bytes", "source_pose_bytes", "air_ticks")},
                "unique_pattern_pool_bytes_all_poses": len(unique_patterns) * 64,
                "worst_pose_upload_ticks_at_64B_per_frame":
                    (worst["selected_bytes"] + STREAM_CHUNK_BYTES - 1) // STREAM_CHUNK_BYTES,
                "poses_upload_ticks_exceed_air_duration": len(timing_mismatches),
                "metadata_and_pattern_remap_exact": all(
                    row["metadata_remap_exact"] and row["pattern_remap_exact"] for row in rows),
                "palette_specific_metadata_verified": all(
                    row["palette_metadata_verified"] for row in rows),
            }

    per_actor_buffer = {}
    for palette, fighter in pilot_profiles.items():
        states = list(all_poses[(fighter, palette)].values())
        # Every current pose may transition to any selected next pose or facing;
        # no transition graph is proven yet, so this intentionally overbounds.
        worst = None
        for current in states:
            current_patterns = set(current["selected_patterns"])
            for following in states:
                joined = current_patterns | set(following["selected_patterns"])
                candidate = (len(joined), current, following)
                if worst is None or candidate[0] > worst[0]:
                    worst = candidate
        count, current, following = worst
        per_actor_buffer[f"{fighter}_{palette}"] = {
            "transition_scope": "any selected current pose/facing to any selected next pose/facing",
            "current": {key: current[key] for key in ("action", "frame", "facing")},
            "next": {key: following[key] for key in ("action", "frame", "facing")},
            "resident_unique_patterns": count,
            "resident_bytes": count * 64,
            "palette_specific_metadata_verified": all(
                row["palette_metadata_verified"] for row in states),
        }

    transition_prefetch = {}
    for palette, fighter in pilot_profiles.items():
        manifest_key = fighter
        manifest = manifests[manifest_key]
        poses = all_poses[(fighter, palette)]
        for facing in ("right", "left"):
            transitions = []
            for role in manifest["roles"]:
                action = int(role["action"])
                count = int(role["frame_count"])
                loop = role.get("loop_start")
                for frame_index in range(count):
                    if frame_index + 1 < count:
                        next_index = frame_index + 1
                    elif loop is not None:
                        next_index = int(loop)
                    else:
                        continue
                    current = poses[(action, frame_index, facing)]
                    following = poses[(action, next_index, facing)]
                    metrics = _transition_cache_metrics(
                        set(current["selected_patterns"]),
                        set(following["selected_patterns"]),
                        int(current["air_ticks"]))
                    transitions.append({
                        "role": role["role"], "action": action,
                        "from_frame": frame_index, "to_frame": next_index,
                        **metrics,
                    })
            transition_prefetch[f"{fighter}_{palette}_{facing}"] = {
                "transition_count": len(transitions),
                "transitions_exceeding_assumed_chunk": sum(
                    not row["fits_assumed_chunk"] for row in transitions),
                "max_minimum_uniform_upload_bytes_per_vblank": max(
                    (row["minimum_uniform_upload_bytes_per_vblank"] or 0
                     for row in transitions), default=0),
                "transitions": transitions,
                "scope": "consecutive same-facing AIR transitions; exact selected 8x16 byte pairs; assumes all newly needed pairs are prefetched evenly during the current frame duration; does not measure available VBlank throughput or runtime remapping",
            }

    idle_cache_plans = {}
    for palette, fighter, slot_base in (("p1", "ken", 0),
                                         ("p2", "ryu", 64)):
        idle_role = next(role for role in manifests[fighter]["roles"]
                         if role["role"] == "idle")
        idle_cache_plans[f"{fighter}_{palette}"] = _idle_cache_plan(
            all_poses[(fighter, palette)], idle_role,
            "right" if palette == "p1" else "left", slot_base, 64)

    def worst_residency(states: list[dict], facing: str | None = None) -> dict:
        if facing is not None:
            states = [state for state in states if state["facing"] == facing]
        worst = None
        for current in states:
            current_patterns = set(current["selected_patterns"])
            for following in states:
                count = len(current_patterns | set(following["selected_patterns"]))
                if worst is None or count > worst[0]:
                    worst = (count, current, following)
        count, current, following = worst
        return {
            "resident_unique_patterns": count,
            "resident_bytes": count * 64,
            "current": {key: current[key] for key in ("action", "frame", "facing", "role")},
            "next": {key: following[key] for key in ("action", "frame", "facing", "role")},
        }

    residency_scenarios = {}
    start_facing = {"p1": "right", "p2": "left"}
    for palette, fighter in pilot_profiles.items():
        states = list(all_poses[(fighter, palette)].values())
        target_facing = start_facing[palette]
        role_rows = {}
        for role in sorted({state["role"] for state in states}):
            group = [state for state in states if state["role"] == role]
            role_rows[role] = {
                "frames_across_both_facings": len(group),
                "unique_pattern_pool_bytes_both_facings": len({
                    pattern for state in group for pattern in state["selected_patterns"]}) * 64,
                "worst_current_next_both_facings": worst_residency(group),
                "same_facing_current_next": worst_residency(
                    [state for state in group if state["facing"] == target_facing]),
            }
        residency_scenarios[f"{fighter}_{palette}"] = {
            "startup_facing": target_facing,
            "startup_idle_current_next": worst_residency(
                [state for state in states if state["role"] == "idle" and
                 state["facing"] == target_facing]),
            "same_facing_any_action_current_next": worst_residency(
                states, target_facing),
            "any_action_any_facing_current_next": worst_residency(states),
            "per_role": role_rows,
        }

    p1_states = list(all_poses[("ken", "p1")].values())
    p2_states = list(all_poses[("ryu", "p2")].values())
    p1_patterns = {pattern for state in p1_states
                   for pattern in state["selected_patterns"]}
    p2_patterns = {pattern for state in p2_states
                   for pattern in state["selected_patterns"]}
    cross_actor_shared_patterns = p1_patterns & p2_patterns

    def transition_signatures(states: list[dict], role: str | None = None,
                              facing: str | None = None) -> dict[frozenset, dict]:
        allowed = [state for state in states
                   if (role is None or state["role"] == role) and
                   (facing is None or state["facing"] == facing)]
        signatures = {}
        for current in allowed:
            current_patterns = set(current["selected_patterns"])
            for following in allowed:
                resident = current_patterns | set(following["selected_patterns"])
                shared = frozenset(resident & cross_actor_shared_patterns)
                outside = len(resident) - len(shared)
                row = {"outside_shared_pool_patterns": outside,
                       "resident_patterns": len(resident),
                       "current": {key: current[key] for key in
                                   ("action", "frame", "facing", "role")},
                       "next": {key: following[key] for key in
                                ("action", "frame", "facing", "role")}}
                if shared not in signatures or outside > signatures[shared]["outside_shared_pool_patterns"]:
                    signatures[shared] = row
        return signatures

    def combine_actor_transitions(p1_filter: tuple[str | None, str | None],
                                  p2_filter: tuple[str | None, str | None]) -> dict:
        p1_signatures = transition_signatures(p1_states, *p1_filter)
        p2_signatures = transition_signatures(p2_states, *p2_filter)
        worst = None
        for p1_shared, p1_row in p1_signatures.items():
            for p2_shared, p2_row in p2_signatures.items():
                combined_shared = p1_shared | p2_shared
                combined_count = _joint_resident_pattern_count(
                    p1_row["outside_shared_pool_patterns"], p1_shared,
                    p2_row["outside_shared_pool_patterns"], p2_shared)
                if worst is None or combined_count > worst[0]:
                    worst = (combined_count, p1_shared, p1_row,
                             p2_shared, p2_row, combined_shared)
        count, p1_shared, p1_row, p2_shared, p2_row, combined_shared = worst
        additive = p1_row["resident_patterns"] + p2_row["resident_patterns"]
        return {
            "p1": p1_row, "p2": p2_row,
            "p1_resident_bytes_without_cross_actor_dedup": p1_row["resident_patterns"] * 64,
            "p2_resident_bytes_without_cross_actor_dedup": p2_row["resident_patterns"] * 64,
            "shared_patterns_reused_across_actors": len(p1_shared & p2_shared),
            "shared_pattern_bytes_saved": (additive - count) * 64,
            "both_fighters_bytes_after_exact_global_dedup": count * 64,
            "available_sprite_pattern_vram_bytes": SPRITE_PATTERN_BYTES_CURRENT,
            "fits_by_byte_count": count * 64 <= SPRITE_PATTERN_BYTES_CURRENT,
            "global_pattern_table_bytes": len(combined_shared) * 64,
        }

    globally_deduplicated_scenarios = {
        "startup_idle_current_next": combine_actor_transitions(
            ("idle", "right"), ("idle", "left")),
        "same_facing_any_action_current_next": combine_actor_transitions(
            (None, "right"), (None, "left")),
        "any_action_any_facing_current_next": combine_actor_transitions(
            (None, None), (None, None)),
    }

    p2_metadata_reconstruction = {
        fighter: _p2_metadata_reconstruction_probe(
            prefix, manifests[manifest_key], arrays, header_text,
            image_data, bank_start, bank_count)
        for fighter, (prefix, manifest_key) in fighter_specs.items()
    }

    slot_peaks = {}
    for palette in ("p1", "p2"):
        slot_peaks[palette] = per_actor_buffer[f"{pilot_profiles[palette]}_{palette}"]
    two_actor_bytes = slot_peaks["p1"]["resident_bytes"] + slot_peaks["p2"]["resident_bytes"]
    scenario_totals = {}
    for scenario in ("startup_idle_current_next",
                     "same_facing_any_action_current_next",
                     "any_action_any_facing_current_next"):
        p1_size = residency_scenarios["ken_p1"][scenario]["resident_bytes"]
        p2_size = residency_scenarios["ryu_p2"][scenario]["resident_bytes"]
        scenario_totals[scenario] = {
            "p1_bytes": p1_size, "p2_bytes": p2_size,
            "both_fighters_bytes": p1_size + p2_size,
            "available_sprite_pattern_vram_bytes": SPRITE_PATTERN_BYTES_CURRENT,
            "candidate_fits": p1_size + p2_size <= SPRITE_PATTERN_BYTES_CURRENT,
            "candidate_fit_proven": False,
        }
    available = SPRITE_PATTERN_BYTES_CURRENT
    return {
        "model": "extract only pattern pairs referenced by one facing; compact ids; preserve dx/dy and exact 64-byte source patterns",
        "palette_facing_pose_variants": variants,
        "variant_compatibility": variant_compatibility,
        "p2_metadata_reconstruction_probe": p2_metadata_reconstruction,
        "rejected_variants": rejected_variants,
        "unrestricted_transition_residency": per_actor_buffer,
        "transition_prefetch": transition_prefetch,
        "idle_cache_plan": idle_cache_plans,
        "residency_scenarios": residency_scenarios,
        "two_actor_scenario_totals": scenario_totals,
        "cross_actor_pattern_intersection": {
            "unique_patterns_in_both_complete_pools": len(cross_actor_shared_patterns),
            "potential_shared_pool_bytes": len(cross_actor_shared_patterns) * 64,
            "patterns": [{
                "sha256": hashlib.sha256(pattern).hexdigest(),
                "nonzero_bytes": sum(value != 0 for value in pattern),
                "fully_transparent_pair": not any(pattern),
            } for pattern in sorted(cross_actor_shared_patterns)],
            "scope": "byte-identical pattern pairs only; candidate requires one shared VRAM index and per-pose metadata remap",
        },
        "global_pattern_dedup_scenarios": globally_deduplicated_scenarios,
        "two_actor_candidate": {
            "p1_palette_worst_actor": next(key for key, row in per_actor_buffer.items()
                                             if row is slot_peaks["p1"]),
            "p2_palette_worst_actor": next(key for key, row in per_actor_buffer.items()
                                             if row is slot_peaks["p2"]),
            "p1_current_plus_next_bytes": slot_peaks["p1"]["resident_bytes"],
            "p2_current_plus_next_bytes": slot_peaks["p2"]["resident_bytes"],
            "current_and_next_for_both_fighters_bytes": two_actor_bytes,
            "available_sprite_pattern_vram_bytes": available,
            "fits_candidate_budget": two_actor_bytes <= available,
            "palette_specific_metadata_verified": all(
                row["palette_specific_metadata_verified"] for row in per_actor_buffer.values()),
            "budget_fit_proven": False,
            "runtime_implemented_or_emulator_proved": False,
        },
        "scope": "pilot matchup Ken P1 plus Ryu P2; maximum uses any-to-any frame/facing transition, 64 B/frame upload assumption, excludes stage/HUD/effects and VRAM reservations; pattern bytes, dx/dy remapping, and palette-specific P2 metadata are checked against exported data, but remapping and upload are not implemented or emulator-proved",
    }


def _macro_int(header: str, symbol: str) -> int:
    match = re.search(rf"^#define\s+{re.escape(symbol)}\s+(\d+)\s*$",
                      header, re.M)
    if not match:
        raise ValueError(f"generated pattern macro is missing: {symbol}")
    return int(match.group(1))


def _load_pose_patterns(header: str, bank_dir: Path,
                        bank_files: dict[int, str], prefix: str,
                        action: int, frame: int, palette: str,
                        bank_cache: dict[Path, bytes]) -> bytes:
    if palette not in ("p1", "p2"):
        raise ValueError(f"unsupported fighter palette: {palette}")
    suffix = "_P2_TILES" if palette == "p2" else "_TILES"
    symbol = f"{prefix}_A{action}F{frame}{suffix}"
    bank = _macro_int(header, symbol + "_BANK")
    offset = _macro_int(header, symbol + "_OFF")
    size = _macro_int(header, symbol + "_SIZE")
    bank_file = bank_files.get(bank)
    if bank_file is None:
        raise ValueError(f"pattern bank {bank} is absent from its manifest")
    path = bank_dir / bank_file
    if path not in bank_cache:
        bank_cache[path] = path.read_bytes()
    blob = bank_cache[path]
    if offset < 0 or size < 0 or offset + size > len(blob) or size % 64:
        raise ValueError(f"invalid 8x16 pattern range for {symbol}")
    return blob[offset:offset + size]


def _rasterize_pose_opacity(patterns: bytes, sprites: list[dict],
                            screen_w: int = 256,
                            screen_h: int = 192) -> bytes:
    """Rasterize nontransparent pixels from SMS 4bpp patterns + 8x16 META."""
    if len(patterns) % 32:
        raise ValueError("pattern payload is not a whole number of 8x8 tiles")
    pixels = bytearray(screen_w * screen_h)
    for sprite in sprites:
        x0, y0 = int(sprite["x"]), int(sprite["y"])
        tile = int(sprite["tile"])
        for half in range(2):
            offset = (tile + half) * 32
            if offset < 0 or offset + 32 > len(patterns):
                raise ValueError("metasprite references outside its frame patterns")
            top = y0 + half * 8
            for py in range(8):
                sy = top + py
                if sy < 0 or sy >= screen_h:
                    continue
                row = offset + py * 4
                for px in range(8):
                    sx = x0 + px
                    if sx < 0 or sx >= screen_w:
                        continue
                    bit = 1 << (7 - px)
                    if any(patterns[row + plane] & bit for plane in range(4)):
                        pixels[sy * screen_w + sx] = 1
    return bytes(pixels)


def _idle_animation_envelope(header: str, bank_dir: Path,
                             manifest: dict, poses: dict[tuple[int, int], dict],
                             prefix: str, palette: str) -> bytes:
    idle = next((role for role in manifest["roles"]
                 if role.get("role") == "idle"), None)
    if idle is None:
        raise ValueError("fighter manifest has no idle role")
    bank_files = {int(row["bank"]): str(row["file"])
                  for row in manifest["banks"]}
    bank_cache: dict[Path, bytes] = {}
    envelope = bytearray(256 * 192)
    for frame in range(int(idle["frame_count"])):
        pose = poses[(int(idle["action"]), frame)]
        patterns = _load_pose_patterns(
            header, bank_dir, bank_files, prefix, int(idle["action"]),
            frame, palette, bank_cache)
        raster = _rasterize_pose_opacity(patterns, pose["sprites"])
        for index, opaque in enumerate(raster):
            if opaque:
                envelope[index] = 1
    return bytes(envelope)


def _video_pose_fidelity(video_path: Path,
                         expected_masks: dict[str, bytes]) -> dict:
    import cv2
    import numpy as np

    capture = cv2.VideoCapture(str(video_path))
    if not capture.isOpened():
        raise ValueError(f"cannot open pilot video: {video_path}")
    observed = None
    frame_count = 0
    dimensions = None
    while True:
        ok, frame = capture.read()
        if not ok:
            break
        height, width = frame.shape[:2]
        if dimensions is None:
            dimensions = [width, height]
            observed = np.zeros((height, width), dtype=bool)
        elif dimensions != [width, height]:
            capture.release()
            raise ValueError("pilot video changes framebuffer dimensions")
        observed |= np.any(frame[:, :, :3] != 0, axis=2)
        frame_count += 1
    capture.release()
    if observed is None or frame_count == 0:
        raise ValueError("pilot video contains no decodable frames")
    if dimensions != [256, 192]:
        raise ValueError(f"expected 256x192 VDP framebuffer, got {dimensions}")

    fighters = {}
    for name, expected_bytes in expected_masks.items():
        if len(expected_bytes) != observed.shape[0] * observed.shape[1]:
            raise ValueError(f"expected animation mask has wrong canvas: {name}")
        expected_canvas = np.frombuffer(expected_bytes, dtype=np.uint8).reshape(
            observed.shape) > 0
        ys, xs = np.where(expected_canvas)
        if not len(xs):
            raise ValueError(f"expected animation mask is empty: {name}")
        margin = 8
        x0, x1 = max(0, int(xs.min()) - margin), min(
            observed.shape[1], int(xs.max()) + margin + 1)
        y0, y1 = max(0, int(ys.min()) - margin), min(
            observed.shape[0], int(ys.max()) + margin + 1)
        expected = expected_canvas[y0:y1, x0:x1]
        actual = observed[y0:y1, x0:x1]
        intersection = int(np.logical_and(expected, actual).sum())
        union = int(np.logical_or(expected, actual).sum())
        iou = intersection / union if union else 1.0
        fighters[name] = {
            "position": [x0, y0], "size": [x1 - x0, y1 - y0],
            "expected_opaque_pixels": int(expected.sum()),
            "observed_nonblack_pixels": int(actual.sum()),
            "intersection_pixels": intersection, "mask_iou": round(iou, 6),
            "pass": iou >= 0.995,
        }
    capture_metadata = video_path.with_suffix(".json")
    metadata = (json.loads(capture_metadata.read_text(encoding="utf-8"))
                if capture_metadata.is_file() else {})
    return {
        "video": str(video_path), "frames": frame_count,
        "video_sha256": hashlib.sha256(video_path.read_bytes()).hexdigest(),
        "capture_metadata": str(capture_metadata) if metadata else None,
        "capture_rom": metadata.get("rom"),
        "framebuffer": dimensions,
        "method": "temporal union against rasterized union of all expected idle AIR poses",
        "fighters": fighters,
        "status": "pass" if all(row["pass"] for row in fighters.values()) else "fail",
        "scope": "black-background pilot: idle-animation envelope and pivot only; does not validate stage occlusion, pose order, AIR timing, flicker duty, or 50/60 FPS",
    }


def audit(versus_manifest: Path, floor_y: int = 160,
          video_path: Path | None = None) -> dict:
    root = versus_manifest.parent
    combined = json.loads(versus_manifest.read_text(encoding="utf-8"))
    header_path = Path(combined["header"])
    if not header_path.is_absolute():
        # Generator manifests store workspace-relative paths.
        workspace_path = Path.cwd() / header_path
        if workspace_path.is_file():
            header_path = workspace_path
        else:
            header_path = root / header_path.name
    header_text = header_path.read_text(encoding="ascii")
    arrays = _arrays(header_text)
    pattern_sizes = {}
    size_def = re.compile(r"#define\s+(\w+_TILES(?:_P2)?)_SIZE\s+(\d+)")
    for symbol, size in size_def.findall(header_text):
        pattern_sizes[symbol.removesuffix("_P2") if symbol.endswith("_P2") else symbol] = int(size)
    # The generator spells the palette variant as _P2_TILES, so normalize the
    # alternate-size macro to the same lookup key used below.
    for symbol, size in re.findall(
            r"#define\s+(\w+_P2_TILES)_SIZE\s+(\d+)",
            header_text):
        pattern_sizes[symbol] = int(size)

    p1_path = root / "p1_ken" / "ken_scene_manifest.json"
    p2_path = root / "p2_ryu" / "ken_scene_manifest.json"
    p1_manifest = json.loads(p1_path.read_text(encoding="utf-8"))
    p2_manifest = json.loads(p2_path.read_text(encoding="utf-8"))
    p1_prefix = "KENMASTERSADV"
    p2_prefix = "RYU_KANG"
    p1_poses = _fighter_poses(p1_prefix, p1_manifest, arrays,
                              96, floor_y, 0, "p1", pattern_sizes)
    p2_poses = _fighter_poses(p2_prefix, p2_manifest, arrays,
                              152, floor_y, 1, "p2", pattern_sizes)
    p2_visual_poses = _fighter_poses(p2_prefix, p2_manifest, arrays,
                                     160, floor_y, 1, "p2", pattern_sizes)
    p1_frame0 = _fighter_poses(p1_prefix, p1_manifest, arrays,
                               96, floor_y, 0, "p1", pattern_sizes)[(0, 0)]
    # The ROM diagnostic uses a distinct anchor for P2 to keep its silhouette
    # clear of P1; the budget simulation above intentionally keeps the tighter
    # combat spacing.
    p2_frame0 = _fighter_poses(p2_prefix, p2_manifest, arrays,
                               160, floor_y, 1, "p2", pattern_sizes)[(0, 0)]

    single_worst = {"p1_ken": None, "p2_ryu": None}
    for key, poses in (("p1_ken", p1_poses), ("p2_ryu", p2_poses)):
        single_worst[key] = max(poses.values(), key=lambda item: (
            item["metrics"]["sat_entries"],
            item["metrics"]["peak_sprites_per_scanline"]))

    pair_worst_sat = None
    pair_worst_line = None
    idle_pair = None
    for p1 in p1_poses.values():
        for p2 in p2_poses.values():
            sprites = p1["sprites"] + p2["sprites"]
            metrics = _screen_metrics(sprites)
            candidate = {"p1": {k: p1[k] for k in ("role", "action", "frame")},
                         "p2": {k: p2[k] for k in ("role", "action", "frame")},
                         "metrics": metrics, "sprites": sprites}
            if pair_worst_sat is None or metrics["sat_entries"] > pair_worst_sat["metrics"]["sat_entries"]:
                pair_worst_sat = candidate
            if (pair_worst_line is None or
                    metrics["peak_sprites_per_scanline"] >
                    pair_worst_line["metrics"]["peak_sprites_per_scanline"]):
                pair_worst_line = candidate
            if p1["role"] == p2["role"] == "idle" and (
                    idle_pair is None or
                    metrics["peak_sprites_per_scanline"] >
                    idle_pair["metrics"]["peak_sprites_per_scanline"]):
                idle_pair = candidate

    timing = (_stream_mismatches("ken", p1_manifest) +
              _stream_mismatches("ryu", p2_manifest))
    facing_pool = _facing_pool_audit(
        root, combined, {"ken": p1_manifest, "ryu": p2_manifest},
        arrays, header_text)
    max_pose_bytes = max(pattern_sizes.values(), default=0)
    stride_tiles = ((max_pose_bytes + 31) // 32 + 1) & ~1
    stream_vram_bytes = stride_tiles * 32 * 4  # two buffers for each of two fighters
    bank_bytes = len(combined["banks"]) * 16384
    result = {
        "schema": "sms_scale_pilot_audit_v1",
        "status": "blocked" if (pair_worst_line["metrics"]["violations"] or
                                  pair_worst_sat["metrics"]["violations"] or
                                  stream_vram_bytes > SPRITE_PATTERN_BYTES_CURRENT or
                                  not facing_pool["two_actor_candidate"]["fits_candidate_budget"] or
                                  not facing_pool["two_actor_candidate"]["palette_specific_metadata_verified"] or
                                  bool(facing_pool["rejected_variants"]) or
                                  max(len(a["sprites"]) for a in
                                      (single_worst["p1_ken"], single_worst["p2_ryu"])) * 3 + 1 >
                                  SPRITE_META_BYTES_CURRENT or timing) else "measured",
        "source_sha256": combined["source_sha256"],
        "profile": combined.get("fighter_scale"),
        "rom_candidate_banked_bytes": bank_bytes,
        "bank_count": len(combined["banks"]),
        "single_fighter_worst": {key: {
            "role": value["role"], "action": value["action"], "frame": value["frame"],
            "metrics": value["metrics"], "pose_bytes": value["pose_bytes"]}
            for key, value in single_worst.items()},
        "idle_pair": {"p1": idle_pair["p1"], "p2": idle_pair["p2"],
                      "metrics": idle_pair["metrics"]},
        "all_pair_worst_sat": {"p1": pair_worst_sat["p1"], "p2": pair_worst_sat["p2"],
                               "metrics": pair_worst_sat["metrics"]},
        "all_pair_worst_scanline": {"p1": pair_worst_line["p1"], "p2": pair_worst_line["p2"],
                                    "metrics": pair_worst_line["metrics"]},
        "streaming": {"max_pose_bytes": max_pose_bytes,
                      "max_pose_tiles": (max_pose_bytes + 31) // 32,
                      "buffer_stride_tiles_even": stride_tiles,
                      "double_buffers_2_fighters_bytes": stream_vram_bytes,
                      "available_sprite_pattern_vram_bytes": SPRITE_PATTERN_BYTES_CURRENT,
                      "chunk_bytes_per_frame_per_fighter": STREAM_CHUNK_BYTES,
                      "frames_whose_stream_exceeds_air_duration": len(timing),
                      "worst_air_vs_stream": max(timing, key=lambda item: item["stream_ticks"] - item["air_ticks"])
                      if timing else None,
                      "exact_air_timing_proved_in_runtime": not bool(timing)},
        "idle_tile_pool": _idle_family_tile_pool(
            root, combined, {"ken": p1_manifest, "ryu": p2_manifest}, header_text),
        "selected_facing_pool": facing_pool,
        "meta_ram": {"current_bytes_per_fighter": SPRITE_META_BYTES_CURRENT,
                     "candidate_required_max_bytes": max(
                         (len(pose["sprites"]) * 3 + 1
                          for pose in list(p1_poses.values()) + list(p2_poses.values())),
                         default=1)},
        "expected_blockers": [
            "Flicker/sprite scheduling must keep <=8 sprites on every active scanline.",
            "Current VRAM streamer must fit both double buffers in the 8 KiB sprite pattern region.",
            "Selected-facing remapping is a source-derived candidate only; prove its transfer budget and runtime behavior before adopting it.",
            "Cross-actor pattern reuse is only byte-count potential; allocate a shared VDP index, prove remapped metadata, and preserve VRAM headroom before adoption.",
            "P1/P2 metasprite indexes must be validated against the exact palette-specific tile pool; generated P2 pools cannot inherit P1 indices by resemblance.",
            "Current metasprite RAM must hold the largest generated pose.",
            "Runtime must display every pose for its authored AIR duration."
        ],
        "scenes": {
            "idle_pair": {"sprite_size": "8x16", "zoomed": False,
                          "screen_h": 192, "sprites": idle_pair["sprites"]},
            "worst_scanline": {"sprite_size": "8x16", "zoomed": False,
                               "screen_h": 192, "sprites": pair_worst_line["sprites"]},
            "worst_sat": {"sprite_size": "8x16", "zoomed": False,
                          "screen_h": 192, "sprites": pair_worst_sat["sprites"]}
        }
    }
    result["frames_scanned"] = len(p1_manifest["frames"]) + len(p2_manifest["frames"])
    if video_path is not None:
        expected_masks = {
            "ken": _idle_animation_envelope(
                header_text, p1_path.parent, p1_manifest, p1_poses,
                p1_prefix, "p1"),
            "ryu": _idle_animation_envelope(
                header_text, p2_path.parent, p2_manifest, p2_visual_poses,
                p2_prefix, "p2"),
        }
        result["idle_animation_envelope_video_fidelity"] = _video_pose_fidelity(
            video_path, expected_masks)
    return result


def _self_check() -> None:
    assert mirrored_origin_x(152, -27, 31) == 147
    assert mirrored_origin_x(152, -27, 32) == 147
    assert mirrored_origin_x(152, -27, 51) == 123
    assert raster_origin_x(160, -18, 31, True) == 147
    assert raster_origin_x(96, -3, 51, False) == 93
    pair = bytearray(64)
    pair[0] = 0x80
    opacity = _rasterize_pose_opacity(bytes(pair), [
        {"x": 0, "y": 0, "tile": 0}])
    assert opacity[0] == 1 and sum(opacity) == 1
    assert _rasterize_pose_opacity(bytes(64), [
        {"x": 0, "y": 0, "tile": 0}]).count(1) == 0
    pool = _tile_family_metrics([(0, bytes(64)),
                                 (1, bytes(32) + bytes([1]) * 32)])
    assert pool["unique_patterns"] == 2
    assert pool["adjacent_transitions"] == [
        {"from_frame": 0, "to_frame": 1, "changed_tile_slots": 1}]
    assert _pattern_match_counts(bytes([0x21]) * 64,
                                 [bytes([0x43]) * 64]) == (0, 1)
    assert _pattern_match_counts(bytes([0x21]) * 64,
                                 [bytes([0x43]) * 64, bytes([0x21]) * 64]) == (1, 2)
    try:
        _pattern_match_counts(bytes(32), [bytes(64)])
    except ValueError:
        pass
    else:
        raise AssertionError("non-pair input must be rejected by P2 reconstruction probe")
    shared_pair = bytes(64)
    assert not any(shared_pair)  # transparent 8x16 pattern pair
    assert _joint_resident_pattern_count(2, {shared_pair}, 3, {shared_pair}) == 6
    assert _joint_resident_pattern_count(2, {shared_pair}, 3, set()) == 6
    distinct_pair = bytes([1]) * 64
    assert _joint_resident_pattern_count(2, {shared_pair}, 3, {distinct_pair}) == 7
    transition = _transition_cache_metrics(
        {shared_pair, distinct_pair},
        {shared_pair, bytes([2]) * 64}, 4)
    assert transition["reused_pairs"] == 1
    assert transition["next_pose_upload_bytes"] == 64
    assert transition["minimum_uniform_upload_bytes_per_vblank"] == 16
    assert transition["current_plus_next_resident_bytes"] == 192
    assert transition["fits_assumed_chunk"]
    try:
        _transition_cache_metrics({bytes(32)}, {bytes(64)}, 4)
    except ValueError:
        pass
    else:
        raise AssertionError("transition cache must reject non-pair patterns")

    remapped_fixture = _remap_compact_metadata(
        bytes((1, 2, 0, 3, 4, 2, 0x80)), [7, 9])
    assert remapped_fixture == bytes((1, 2, 14, 3, 4, 18, 0x80))
    try:
        _remap_compact_metadata(bytes((1, 2, 4, 0x80)), [7, 9])
    except ValueError:
        pass
    else:
        raise AssertionError("metadata remap must reject missing compact pattern IDs")

    cache_a, cache_b, cache_c = (bytes([value]) * 64 for value in (10, 11, 12))
    cache_pose = lambda frame, patterns, source_ids: {
        "selected_patterns": patterns,
        "selected_pattern_source_pair_indices": source_ids,
        "pattern_bank": 2, "pattern_off": 1024,
        "compact_metadata": [0, 0, 0, 8, 0, 2, 0x80],
        "axis_bytes": [4, 0, 252, 255],
        "axis_signed_xy": [4, -4], "air_ticks": 4,
    }
    idle_fixture = {
        (0, 0, "right"): cache_pose(0, [cache_a, cache_b], [0, 1]),
        (0, 1, "right"): cache_pose(1, [cache_b, cache_c], [1, 2]),
    }
    idle_plan = _idle_cache_plan(
        idle_fixture, {"role": "idle", "action": 0, "frame_count": 2,
                      "loop_start": 0}, "right", 0, 3)
    assert idle_plan["initial_pose"]["pattern_loads"] == [
        {"source_bank": 2, "source_off": 1024, "source_pair_index": 0,
         "target_pair_slot": 0, "bytes": 64},
        {"source_bank": 2, "source_off": 1088, "source_pair_index": 1,
         "target_pair_slot": 1, "bytes": 64},
    ]
    assert idle_plan["transitions"][0]["reused_pair_count"] == 1
    assert idle_plan["transitions"][0]["uploads"] == [
        {"source_bank": 2, "source_off": 1152, "source_pair_index": 2,
         "target_pair_slot": 2, "bytes": 64},
    ]
    assert idle_plan["transitions"][0]["next_metadata"] == [
        0, 0, 2, 8, 0, 4, 0x80]
    assert idle_plan["transitions"][0]["next_pattern_slots"] == [
        {"pattern_sha256": hashlib.sha256(cache_b).hexdigest(),
         "source_pair_index": 1, "target_pair_slot": 1},
        {"pattern_sha256": hashlib.sha256(cache_c).hexdigest(),
         "source_pair_index": 2, "target_pair_slot": 2},
    ]
    assert idle_plan["initial_pose"]["axis_bytes"] == [4, 0, 252, 255]
    assert idle_plan["initial_pose"]["axis_signed_xy"] == [4, -4]

    mini_meta = bytes((0, 0, 4, 8, 0, 0, 16, 0, 6, 0x80))
    mini_metal = bytes((0, 0, 2, 8, 0, 6, 0x80))
    mini_header = "\n".join((
        "#define TEST_A1F0_TILES_SIZE 256",
        "#define TEST_A1F0_TILES_BANK 2",
        "#define TEST_A1F0_TILES_OFF 0",
    ))
    mini_payload = (bytes([0]) * 64 + bytes([1]) * 64 +
                    bytes([2]) * 64 + bytes([2]) * 64)
    mini_poses = _selected_facing_pose_metrics(
        "TEST", "fixture", "p1",
        {"roles": [{"action": 1, "frame_count": 1, "role": "idle"}],
         "frames": {"anim:1.0": {"duration_air": 4}}},
        {"TEST_A1F0_AXIS": struct.pack("<hh", -3, 5),
         "TEST_A1F0_META": mini_meta, "TEST_A1F0_METAL": mini_metal},
        mini_header, mini_payload, 2, 1)
    assert mini_poses[(1, 0, "right")]["selected_pairs"] == 2
    assert mini_poses[(1, 0, "right")]["metadata_remap_exact"]
    assert mini_poses[(1, 0, "right")]["axis_signed_xy"] == [-3, 5]
    assert mini_poses[(1, 0, "left")]["selected_pairs"] == 2
    assert mini_poses[(1, 0, "left")]["metadata_remap_exact"]
    p2_meta = bytes((0, 0, 2, 8, 0, 6, 0x80))
    mini_header_p2 = mini_header + "\n" + "\n".join((
        "#define TEST_A1F0_P2_TILES_SIZE 256",
        "#define TEST_A1F0_P2_TILES_BANK 2",
        "#define TEST_A1F0_P2_TILES_OFF 0",
    ))
    mini_p2 = _selected_facing_pose_metrics(
        "TEST", "fixture", "p2",
        {"roles": [{"action": 1, "frame_count": 1, "role": "idle"}],
         "frames": {"anim:1.0": {"duration_air": 4}}},
        {"TEST_A1F0_AXIS": struct.pack("<hh", -3, 5),
         "TEST_A1F0_META": mini_meta, "TEST_A1F0_METAL": mini_metal,
         "TEST_A1F0_P2_META": p2_meta, "TEST_A1F0_P2_METAL": mini_metal},
        mini_header_p2, mini_payload, 2, 1)
    assert mini_p2[(1, 0, "right")]["palette_metadata_verified"]
    mini_p2_fallback = _selected_facing_pose_metrics(
        "TEST", "fixture", "p2",
        {"roles": [{"action": 1, "frame_count": 1, "role": "idle"}],
         "frames": {"anim:1.0": {"duration_air": 4}}},
        {"TEST_A1F0_AXIS": struct.pack("<hh", -3, 5),
         "TEST_A1F0_META": mini_meta, "TEST_A1F0_METAL": mini_metal},
        mini_header_p2, mini_payload, 2, 1)
    assert not mini_p2_fallback[(1, 0, "right")]["palette_metadata_verified"]

    geometry_manifest = {
        "roles": [{"action": 1, "frame_count": 1, "role": "idle"}],
        "frames": {"anim:1.0": {"size_runtime": [8, 16],
                                 "duration_air": 2, "stream_ticks": 1}},
    }
    geometry_arrays = {
        "TEST_A1F0_AXIS": struct.pack("<hh", 0, 0),
        "TEST_A1F0_META": bytes((1, 2, 0, 0x80)),
        "TEST_A1F0_METAL": bytes((5, 6, 2, 0x80)),
        "TEST_A1F0_P2_META": bytes((7, 8, 4, 0x80)),
        "TEST_A1F0_P2_METAL": bytes((9, 10, 6, 0x80)),
    }
    p1_geometry = _fighter_poses(
        "TEST", geometry_manifest, geometry_arrays, 50, 100, 0, "p1",
        {"TEST_A1F0_TILES": 128})[(1, 0)]
    p2_geometry = _fighter_poses(
        "TEST", geometry_manifest, geometry_arrays, 50, 100, 1, "p2",
        {"TEST_A1F0_P2_TILES": 256})[(1, 0)]
    assert p1_geometry["sprites"][0] == {"x": 51, "y": 102, "tile": 0}
    assert p1_geometry["pose_bytes"] == 128
    assert p2_geometry["sprites"][0] == {"x": 51, "y": 110, "tile": 6}
    assert p2_geometry["pose_bytes"] == 256
    try:
        _fighter_poses(
            "TEST", geometry_manifest,
            {key: value for key, value in geometry_arrays.items()
             if "_P2_" not in key},
            50, 100, 1, "p2", {})
    except ValueError:
        pass
    else:
        raise AssertionError("P2 geometry must not silently fall back to P1 metadata")

    parsed = _arrays("const unsigned char SAMPLE[4] = { 0x00, 0x7f, 0x80, 0xff };\n")
    assert parsed["SAMPLE"] == bytes((0, 127, 128, 255))
    aliased = _arrays(
        "const unsigned char BASE_META[2] = { 1, 128 };\n"
        "#define DUP_META BASE_META\n")
    assert aliased["DUP_META"] == aliased["BASE_META"] == bytes((1, 128))
    try:
        _arrays("#define DUP_META MISSING_META\n")
    except ValueError as exc:
        assert "target is missing" in str(exc)
    else:
        raise AssertionError("metadata alias with missing target must fail")
    try:
        _arrays("#define A_META B_META\n#define B_META A_META\n")
    except ValueError as exc:
        assert "alias cycle" in str(exc)
    else:
        raise AssertionError("metadata alias cycle must fail")
    entries = _sprite_entries(bytes((0xFE, 0xFF, 0x02, 0x80)), 0, 10, 20)
    assert entries == [{"x": 8, "y": 19, "tile": 2}]

    ok = _screen_metrics([{"x": x, "y": 40} for x in range(8)])
    assert ok["peak_sprites_per_scanline"] == 8 and not ok["violations"]
    overflow = _screen_metrics([{"x": x, "y": 40} for x in range(9)])
    assert overflow["peak_sprites_per_scanline"] == 9
    assert "scanline overflow: 9 > 8" in overflow["violations"]

    manifest = {"frames": {
        "anim:0.0": {"duration_air": 1, "stream_ticks": 2},
        "anim:0.1": {"duration_air": 3, "stream_ticks": 2},
    }}
    mismatch = _stream_mismatches("fixture", manifest)
    assert mismatch == [{"fighter": "fixture", "action": 0, "frame": 0,
                         "air_ticks": 1, "stream_ticks": 2}]
    print("[SELF-CHECK OK] padded mirror pivot, palette metadata binding, temporal opacity raster, exact/opacity pair comparison, cross-actor pool reuse, tile remap, scale parser, signed metasprite, line budget, AIR/stream mismatch")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path,
                        help="versus_scene_manifest.json")
    parser.add_argument("--out", type=Path)
    parser.add_argument("--video", type=Path,
                        help="optional black-background pilot video; compares idle envelope/pivot, not AIR timing or flicker")
    parser.add_argument("--floor-y", default=160, type=int)
    parser.add_argument("--require-measured", action="store_true",
                        help="sai com erro se qualquer budget/tempo do corte estiver bloqueado")
    parser.add_argument("--self-check", action="store_true")
    args = parser.parse_args(argv)
    if args.self_check:
        _self_check()
        return 0
    if not args.manifest or not args.out:
        parser.error("--manifest e --out sao obrigatorios fora de --self-check")
    result = audit(args.manifest, args.floor_y, args.video)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n",
                        encoding="utf-8")
    print(f"[MEASURED] scale-pilot status={result['status']} "
          f"idle_peak={result['idle_pair']['metrics']['peak_sprites_per_scanline']}/line "
          f"SAT={result['idle_pair']['metrics']['sat_entries']} "
          f"buffers={result['streaming']['double_buffers_2_fighters_bytes']}/"
          f"{result['streaming']['available_sprite_pattern_vram_bytes']} B "
          f"report={args.out}")
    if args.video:
        fidelity = result["idle_animation_envelope_video_fidelity"]
        print(f"[VIDEO] idle animation envelope/pivot={fidelity['status']} "
              f"frames={fidelity['frames']} report={args.out}")
        if fidelity["status"] != "pass":
            return 1
    return 1 if args.require_measured and result["status"] != "measured" else 0


if __name__ == "__main__":
    raise SystemExit(main())
