#ifndef GRAPHICS_H
#define GRAPHICS_H

#include "globals.h"

void FUNCAO_SCREEN_HEIGHT_APPLY();
void FUNCAO_SPR_POSITION();
void FUNCAO_ANIMACAO();
void FUNCAO_CAMERA_BGANIM();
void FUNCAO_SAMSHOFX();
void CLEAR_VDP();

#endif // GRAPHICS_H
